runtime: java11
entrypoint: java -Xmx512m -jar cloud-1.0.war
instance_class: F2

inbound_services:
  - warmup

handlers:
  - url: /.*
    secure: always
    script: auto

automatic_scaling:
  max_concurrent_requests: 50
  min_pending_latency: 5000ms
  max_pending_latency: 15000ms
  target_cpu_utilization: 0.9
  target_throughput_utilization: 0.9
